create database sistema_tesouro_azul;
use sistema_tesouro_azul;

CREATE TABLE TB_USUARIO_CADASTRO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(35) NOT NULL,
    EMAIL_USUARIO VARCHAR(100) NOT NULL,
    DTA_NASC_USUARIO DATE NOT NULL,
    CPF_USUARIO CHAR(11) NOT NULL,
    CNPJ_USUARIO CHAR(14) NOT NULL,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    FOTO_USUARIO TEXT NOT NULL,
    CONSTRAINT chk_senha_length CHECK (LENGTH(SENHA_USUARIO) BETWEEN 8 AND 255),
    CONSTRAINT unq_email UNIQUE (EMAIL_USUARIO),
    CONSTRAINT unq_cpf UNIQUE (CPF_USUARIO)
);	
